name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Muddle
        uses: demonnic/build-with-muddler@main
        with:
          muddlerVersion: "LATEST"

      - name: Upload MPackage
        uses: actions/upload-artifact@v4
        with:
          name: poopDeck
          path: build/tmp/